apt_packages = [
    "htop",
    "nautilus-dropbox",
    "ncdu",
    "python3",
    "terminator",
    "wget",
]

snap_packages = [
    {name = "nvim", classic = true},
    {name = "steam", classic = false},
    {name = "signal-desktop", classic = false},
    {name = "spotify", classic = false},
    {name = "code", classic = false},
]



[[dotfiles]]
name = "Bashrc"
repo_path = "conf/bashrc"
deploy_path = "~/.bashrc"

[[dotfiles]]
name = "Inputrc"
repo_path = "conf/inputrc"
deploy_path = "~/.inputrc"

[[dotfiles]]
name = "NeoVim configuration"
repo_path = "conf/nvim.lua"
deploy_path = "~/.config/nvim/init.lua"

[[dotfiles]]
name = "Terminator configuration"
repo_path = "conf/terminator"
deploy_path = "~/.config/terminator/config"
