#!/usr/bin/env python3.6

""" Installer of the dotfiles setup """

import os
import sys

def main():
    " Main function for the installation"

    # Get source path to obtain the configuration files from
    source_path_name = "/".join([os.path.dirname(os.path.realpath(__file__)), "/etc"])
    source_path = os.path.normpath(source_path_name)
    # Install configuration files
    from lib import config_file_installer
    config_file_installer.install_config_files(source_path)

    # sys.exit()
    print("DEVELOPMENT MODE IS RUNNING")
    programs_to_install = ["htop"]

    b = os.system("which ncdu")
    print(b)

# Warn the user that this programm wil alter important system files
RUN_PROGRAM = input((
    "\x1b[31mWarning: \x1b[39mThis tool will modify important system files/settings, continue? [y/N] "
)).lower()
#
# Run programm if the user accepts the alteration of files
if RUN_PROGRAM in ("y", "yes"):
    main()
else:
    print("Exitting program without altering any files/settings...")
    sys.exit()
