PRIMARY_COLOR = "#DEDDDA"
DISABLE_COLOR = "#BCBBB8"
PRIMARY_BACKGROUND_COLOR = "#1B1D20"
HOVER_BORDER_COLOR = "#3584E4"
BORDER_RADIUS = "10px"
BORDER_SIZE = "2px"
BUTTON_HEIGHT_INT = 33
BUTTON_HEIGHT = f"{BUTTON_HEIGHT_INT}px"
