
[[packages]]
name="Python"
groups=["Home Basics"]
search_names=["python3"]

[[packages]]
name="Spotify"
groups=["Home Basics"]
search_names=["spotify"]

[[packages]]
name="Terminator"
groups=["Home Basics", "Terminal Tools"]
search_names=["terminator"]

[[packages]]
name="Neovim"
groups=["Home Basics", "Terminal Tools"]
search_names=["nvim", "neovim"]

[[packages]]
name="NCDU"
groups=["Terminal Tools"]
search_names=["ncdu"]

[[packages]]
name="something"
groups=["Terminal Tools"]
search_names=["ncdu"]

[[packages]]
name="NCDU"
groups=["Terminal Tools"]
search_names=["htop"]
